### ISSUE TITLE
Feature Request: Affective Domains

### ISSUE THREAD

**Issue by NikhilPr95** [clemtoy/WNAffect#1]
First of all, thank you so much for this repository! It is of invaluable help to me. Thank you for making this.

Now, I have a request - 
Your repository gives the emotion of an inputted word - However, the wordnet-affect hierarchy contains  seven affective states - physical state, behavior, trait, sensation, situation, signal, mental state,  the children of which are all words in the graph.
It would be convenient if you could add a function get_affective_state, or something similar, that gets the affective state for the given word.

This, of course, should be pretty easy to do myself but it would be a valuable addition to your repository anyway. If I make it before you do, I'll create a pull request for the same. 

Thanks.

P.S. -

I see a simple one line expression returning `emo.get_level(1).name` where emo is an Emotion, will do the trick.

**Comment by clemtoy** [comment]
Hi NikhilPr95,

I am not agree about:

> the wordnet-affect hierarchy contains seven affective states - physical state, behavior, trait, sensation, situation, signal, mental state, the children of which are all words in the graph.

All affective states are not at the 1st level of the tree (e.g. _cognitive-state_).

Moreover, as you said, you can use the `get_level()` function to retrieve the state you are looking for.
That is why I am not convinced about the usefulness of a `get_affective_state()` function.

Anyway, thank you very much for your proposal.

Regards
Clément
